Here we gonna to Learn about python AI & ML contents

# Numpy
 
 * Homogeneous Multidimensional array
 * Used to calculate the scientific calculation

Methods ..
    1. np.array(array,dtype)
    2. np.zeros((r,c))
    3. np.ones((array count,row,col))

    4. np.linspace(start,end,count_numbers)
    5. np.arange(start,end,*val)
    6. __.ndim                                                                         --> Dimension of the array 
    7. np.shape()

In [20]:
import numpy as np


# one dimensional array 
a = np.array([5,6,3,2,3])
print(a.dtype)


# Two dimensional array
b = np.array([(2,3,4,5,6),(5,6,98,9,0)])
print(b)

# Np one's
z = np.zeros((3,3))
print(z)

# Np ones
o = np.ones((3,4,4))
print(o)

# np arrang
ar = np.arange(1,100,3)
print(len(ar))
print(ar)
print(ar.shape)



# np linspace()
l = np.linspace(1,12,8)
print(l)


int64
[[ 2  3  4  5  6]
 [ 5  6 98  9  0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
33
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
(33,)
[ 1.          2.57142857  4.14285714  5.71428571  7.28571429  8.85714286
 10.42857143 12.        ]
